### ISSUE TITLE
Rename RTF

### ISSUE THREAD

**Issue by drdanz** [robotology/robot-testing#101]
* The acronym `RTF` is quite popular, the most accepted is `Rich Text Format`, but there are [many others](https://www.acronymfinder.com/RTF.html) meanings.
* There is a [librtf](http://librtf.sourceforge.net/)

This causes conflicts with other packages, making it impossible to package it properly for debian/ubuntu.

I suggest to rename everything to something else.

* The libraries (`libRTF`, `libRTF_dll`, etc)
* The namespace (`RTF`)
* The include path (`include/rtf`)
* The CMake name (`RTF`)
* The CMake targets and components (`RTF`, `RTF_dll`, ecc)
* Exported CMake variables (`RTF_LIBRARIES`, `RTF_INCLUDE_DIRS`, ecc)
* The `testrunner` executable (`testrunner`)

This is obviously a disruptive change, therefore we need to discuss this, but I believe such a change is required, and we should do this change as soon as possible

Proposal for the names? I was thinking `RoboTF`, but TF in robotics has a different meaning. Maybe `RoboTest`?

**Comment by pattacini** [comment]
What are the conflicts you discovered?

**Comment by drdanz** [comment]
There are too many `librtf-xxx` packages related to rtf files, and the `libRTF.so` file requires a `librtf1` package. Moreover the headers are installed in `/usr/include/rtf`, it's quite confusing

**Comment by traversaro** [comment]
I think expanding all the conflicting uses of the RTF acronym (library robot-testing-framework, headers prefix RobotTestingFramework, cmake package RobotTestingFramework, etc etc) is probably the best option

**Comment by drdanz** [comment]
Perhaps when we do the change we should release it as RobotTestingFramework 2.0?

**Comment by traversaro** [comment]
Good idea.

**Comment by drdanz** [comment]
Actually I'm thinking that `RobotTestingFramework` is a very long name, not good for namespaces, cmake variables, etc. What about `RoboTest`?

**Comment by traversaro** [comment]
I personally would prefer to minimize the changes, and I do not think that `RobotTestingFramework` is too long as a name. By the way, we can also think of just changing the things that are risk more conflicts, such as the CMake package name and the library name, and just keep RTF for anything else.

**Comment by pattacini** [comment]
If we agree to proceed as @drdanz suggested, then I would go for @traversaro's proposal.

cc @lornat75

**Comment by drdanz** [comment]
Ok, if you agree, I'd proceed with:

* Libraries and executables:
```
librobot-testing-framework.so
librobot-testing-framework-dll.so
robot-testing-framework-testrunner
```

* CMake package, targets and variables:
``` cmake
find_package(RobotTestingFramework)
target_link_libraries(foo RobotTestingFramework::RTF RobotTestingFramework::RTF_dll)
message("${RobotTestingFramework_INCLUDE_DIRS}")
message("${RobotTestingFramework_LIBRARIES}")
```

* Include path and namespace
```c++
#include <robot-testing-framework/TestCase.h>
RobotTestingFramework::TestCase
```
this can eventually be simplified during the port by using a namespace alias
```c++
#include <robot-testing-framework/TestCase.h>
namespace RTF = RobotTestingFramework;
RTF::TestCase
```

This is a big breaking change, therefore, if we go with this, we should decide how to proceed with the other repos. I'd like to merge this in master, and release 2.0 ASAP, but then all the other master repo would be broken. Perhaps we should do it together with YARP and iCub releases?

**Comment by traversaro** [comment]
I never saw the hyphen used in the include director, it is ok to use it?

**Comment by drdanz** [comment]
good question... I suppose it is, `ls -d /usr/include/*-*` has several results, even though most of them are just for separating the name and the version.
I don't want to risk though, let's just remove all the `-` (at this point also from the libs)
I'd make also the namespace lowercase, so that it matches with the include dir

* Libraries and executables:
```
librobottestingframework.so
librobottestingframework-dll.so
robottestingframework-testrunner
```

* CMake package, targets and variables:
``` cmake
find_package(RobotTestingFramework)
target_link_libraries(foo RobotTestingFramework::RTF RobotTestingFramework::RTF_dll)
message("${RobotTestingFramework_INCLUDE_DIRS}")
message("${RobotTestingFramework_LIBRARIES}")
```

* Include path and namespace
```c++
#include <robottestingframework/TestCase.h>
robottestingframework::TestCase
```
this can eventually be simplified during the port by using a namespace alias
```c++
#include <robottestingframework/TestCase.h>
namespace RTF = robottestingframework;
RTF::TestCase
```

**Comment by drdanz** [comment]
BTW, I think that for coherence we should rename this repo `robotology/robottestingframework` as well, what do you think

**Comment by traversaro** [comment]
`robot-testing-framework` is probably more consistent with the rest of the repository's names.

**Comment by drdanz** [comment]
Done in #103
