### ISSUE TITLE
verify how to start/stop modules (i.e. simulator) within testing infrastructure

### ISSUE THREAD

**Issue by lornat75** [robotology/robot-testing#2]

**Comment by traversaro** [comment]
It may also be interesting to investigate how to automatically start the yarpserver, it seems a feature users are interested in, see https://github.com/robotology/yarp/issues/394#issuecomment-73023415 .

**Comment by apaikan** [comment]
Well, this is where the RTF becomes useful. A fixture manager can be assigned for every test suits which does the job. For YARP, there is the `yarpmanager` fixture manager implemented in the `icub-tests` repository. A set of modules (simulator, robot interface,...) can be arranged in a XML file  and given to the `yarpmanager` fixture manager in the test suite. The `yarpmanager` runs all the modules, establishes the connections and monitors that the modules are properly running during the test run. If one of the modules crashes (i.e., fixture collapses) during the test run, the `yarpmanager` retry to run the modules and rerun the test suit. Here is an example: 

```xml
<suit name="Camera Test Suite">
    <description> Testing icubSim cameras</description>
    <environment>--robotname icubSim</environment>
    <fixture param="--fixture myapp.xml"> yarpmanager.so </fixture>
    <test param="--from right_camera.ini"> CameraTest.so </test>
    <test param="--from left_camera.ini"> CameraTest.so </test> 
     ...
</suit>
```  
Where `myapp.xml` is a usual `yarpmanager`  application file!

**Comment by apaikan** [comment]
accomplished in the new framework.
