### ISSUE TITLE
headers install directory 

### ISSUE THREAD

**Issue by traversaro** [robotology/robot-testing#20]
All the RTF headers are installed in the `include`  directory, so they are used as:

~~~
#include <TestCase.h>
#include <TestAssert.h>
#include <Arguments.h>
~~~

Could it make sense to move them in `include/rtf` (or `include/RTF`), so we will have:
~~~
#include <rtf/TestCase.h>
#include <rtf/TestAssert.h>
#include <rtf/Arguments.h>
~~~

cc @apaikan

**Comment by apaikan** [comment]
@traversaro well noticed! 
agreed!

**Comment by traversaro** [comment]
I will probably do it in the weekend, so Monday morning @randaz81 and @ale-git can simply update `robot-testing` and `icub-tests` and get everything working.

**Comment by traversaro** [comment]
Done in https://github.com/robotology/robot-testing/issues/22 .
