### ISSUE TITLE
CTest integration

### ISSUE THREAD

**Issue by traversaro** [robotology/robot-testing#23]
To integrate nicely with the traditional CMake/CTest  [`add_test`](http://www.cmake.org/cmake/help/v3.0/command/add_test.html) command, we need that the `testrunner` returns a number different from `0` on failure. 
For this are necessary a bunch of modifications: 
  * [x] For reporting failed test, the `return 0` in https://github.com/robotology/robot-testing/blob/master/src/testrunner/src/main.cpp#L232 should be substituted with `return collector.failedCount();` 
  * [x] For loading errors (i.e. failure of a `load*` method) I guess it make sense to simply return 1.

**Comment by traversaro** [comment]
cc @apaikan

**Comment by lornat75** [comment]
+1

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/robot-testing/commit/35678bdcda725802bb11ce6ca98eb10a814a6f6f . I used `cstdlib` `EXIT_FAILURE` and `EXIT_SUCCESS`.

**Comment by apaikan** [comment]
@traversaro  cool!
