### ISSUE TITLE
Generate Jenkins compatible xml files

### ISSUE THREAD

**Issue by traversaro** [robotology/robot-testing#30]
By writing a class similar to `TextOutputter` but that dumps the test results in a format compatible with Jenkins.

**Comment by traversaro** [comment]
Apparently Jenkins (and also Atlassian Bamboo [1], so @luca-fiorio is happy) are digesting XML files in the JUnit XML format. Apparently there is not clean definition of this format, but a few XSD files around the net show that is a simple format:
https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd


[1] : https://confluence.atlassian.com/display/BAMBOO/JUnit+parsing+in+Bamboo

**Comment by traversaro** [comment]
More info: http://help.catchsoftware.com/display/ET/JUnit+Format .

**Comment by apaikan** [comment]
@traversaro  have you seen this?  http://www.yolinux.com/TUTORIALS/CppUnit.html

There is an example of the Kenkins XML file and how it has been implemented in the CppUnit.

**Comment by traversaro** [comment]
Cool, I  guess for us (given that we have to write an XMLOutputter anyway) it make sense to directly use the JUnit XML format.

**Comment by apaikan** [comment]
@traversaro  Could you have time to take a look at JUnit XML formatter?  I am playing around with that these days because we need to integrate RTF with jenkins. 

Just want be sure that we are not doing the same thing in parallel.

**Comment by traversaro** [comment]
I had a non-working prototype locally, I'll check quickly if it can be finished in the short term!

**Comment by apaikan** [comment]
@traversaro  okay. I have taken a look inside the XML file and apparently it is not complicated. Ill prepare some basic stuffs quickly within this week. You can later continue working on that. :)

**Comment by traversaro** [comment]
Yes, I checked and I did not actually implement anything, so please go ahead!

**Comment by apaikan** [comment]
done in commit d56339fa341f668cdb384fe9f2cf8fe0c6661b21.
