### ISSUE TITLE
Having multiple fixture manager for each suite 

### ISSUE THREAD

**Issue by apaikan** [robotology/robot-testing#54]
It will be useful (and in some cases necessary) to have multiple fixture manager for each suites. Example: 

```xml
<suit name="Basic Tests Suite">
    <description>Testing basic features</description>
    <fixture param="--param myparam"> fixturemanager1 </fixture>
    <fixture param="--param myparam"> fixturemanager2 </fixture>
    ...

    <!-- tests -->
    ...
</suit>

```

**Comment by pattacini** [comment]
Not being this available yet, I struggled to make a single fixture work with all inside. However, this gave me the chance to fix a subtle bug while closing the `cartesiancontrollerserver` component.

Once more let me point out that **RTF** is a magic tool 🥇
I've been using it to create the backbone infrastructure that enables **automatic grading**, in view of VVV17 😄

**Comment by pattacini** [comment]
Well, even though we have multiple fixtures, is there a closing order that we can ensure? Otherwise, we fall back again in the same problem, I'm afraid.
