### ISSUE TITLE
CTest integration v2 

### ISSUE THREAD

**Issue by traversaro** [robotology/robot-testing#57]
To simplify adding tests using `testrunner` to CTest using the `add_test` cmake command, the CMake infrastructure of RTF should provide a variable containing the absolute path to the testrunner binary. 

Helper CMake functions to automatically add a CTest test from a suite would also be convenient.

cc @S-Dafarra

**Comment by traversaro** [comment]
Use case : https://github.com/S-Dafarra/Operational_Control_with_iCub/pull/1/files#diff-15547c54d3d4898a882b4ab7b3cee381R29 .

**Comment by apaikan** [comment]
I have added some simple tests which can be run using `testrunner` via `make test` (see `testing` branch) .
@traversaro and @drdanz  we can elaborate that!

**Comment by S-Dafarra** [comment]
I had an issue using ``make test``: the simulator window appeared and disappeared immediately, making the test fail due to fixtures problems. This issue didn't come out using ``ctest`` though.

**Comment by traversaro** [comment]
cc @aerydna @drdanz

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/robot-testing/pull/88 .

**Comment by apaikan** [comment]
@traversaro  is this issue fixed? :p

**Comment by drdanz** [comment]
We now have a `rtf_add_suite` CMake command, perhaps also an `rtf_add_testcase` could be useful? Otherwise I think this could be closed.

**Comment by traversaro** [comment]
I think the `rtf_add_suite` is enough unless we actually need a `rtf_add_testcase` in a real-world scenario.
