### ISSUE TITLE
How to manage the addition of [[noreturn]] in RTF_ASSERT

### ISSUE THREAD

**Issue by Nicogene** [robotology/robot-testing#66]
Need to discuss how to place this c++11 tag.

**Comment by traversaro** [comment]
I would follow the example of YARP 2.3.72 and just enforce the use of C++11 in RTF headers.

**Comment by drdanz** [comment]
> I would follow the example of YARP 2.3.72 and just enforce the use of C++11 in RTF headers.

+1

**Comment by aerydna** [comment]
solved in #74
