### ISSUE TITLE
FixturePluginLoader test get stuck on Win32 if compiled in Debug

### ISSUE THREAD

**Issue by Nicogene** [robotology/robot-testing#75]
On Windows the test `FixturePluginLoader` get stuck if `RTF` is compiled in Debug.
We should also enable tests on appveyor and the compilation in debug.

**Comment by Nicogene** [comment]
The tests ad several configurations has been added in #76.
With @drdanz we found that in `Debug` configuration the plugin loader tries to load the dlls in `build/Release` folder, without the "d" in the dll name.
For backward compatibility it will be fixed in `devel` branch, in `master` appveyor runs only in `Release`

**Comment by aerydna** [comment]
Fixed by #78
