### ISSUE TITLE
Broken links in Readme

### ISSUE THREAD

**Issue by miccol** [robotology/robot-testing#89]
Hi,

The links under **Tutorials and Examples** are broken.

Cheers,
Michele

**Comment by traversaro** [comment]
Related to https://github.com/robotology/robot-testing/issues/64 .

**Comment by traversaro** [comment]
cc @aerydna @Nicogene  it is sufficient to substitute all the links beginning with `http://robotology.github.io/robot-testing/documentation` with `http://robotology.gitlab.io/docs/rtf/master/` .

**Comment by Nicogene** [comment]
It seems a job for the maintainer :smirk:

**Comment by aerydna** [comment]
fixed
