### ISSUE TITLE
Plugins do not work when -fvisibility=hidden is set

### ISSUE THREAD

**Issue by drdanz** [robotology/robot-testing#93]
RTF_ADD_PLUGIN should force the exporting of the factory symbols

**Comment by traversaro** [comment]
Yep, this is why we have these lines : https://github.com/robotology/yarp/blob/devel/src/rtf-plugins/fixture-managers/yarpmanager/CMakeLists.txt#L10 .

**Comment by drdanz** [comment]
In this case it should be added automatically by the RTF_ADD_PLUGIN command, using `target_compile_definitions`
