### ISSUE TITLE
Improvements to the progress canvas in web-reporter

### ISSUE THREAD

**Issue by drdanz** [robotology/robot-testing#94]
The progress canvas at the bottom left of the web reporter page displays in this order
* A green dot for each successful test
* A red dot for each failed test
* One grey dot for the test currently running

It would be a lot more helpful if it could show the green and the red dots in the correct order, and if the actual number of tests would be shown.

For example if it's currently running test 5 over 8 tests, and all tests passed, except for test 3, the output is:

`G G G R g` (with `G` = green, `R` = red and `g` = grey)

It would be a lot more useful if it was displayed in this way

`G G R G Y g g g` (with `Y` = yellow or some other colour, for the test that is currently running, and `g` = grey for the tests that are not executed yet)

In this way it would be easier to spot the number of the failed test, and the number of tests that are not run yet.

**Comment by aerydna** [comment]
fixed by #95
